import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Card from '#models/card'

export default class extends BaseSeeder {
  public async run () {
    const cartas = [
      { number: 1,  name: 'El Gallo',       url: '/cartas/01 el gallo.jpg' },
      { number: 2,  name: 'El Diablo',      url: '/cartas/02 el diablito.jpg' },
      { number: 3,  name: 'La Dama',        url: '/cartas/03 la dama.jpg' },
      { number: 4,  name: 'El Catrin',      url: '/cartas/04 el catrin.jpg' },
      { number: 5,  name: 'El Paraguas',    url: '/cartas/05 el paraguas.jpg' },
      { number: 6,  name: 'La Sirena',      url: '/cartas/06 la sirena.jpg' },
      { number: 7,  name: 'La Escalera',    url: '/cartas/07 la escalera.jpg' },
      { number: 8,  name: 'La Botella',     url: '/cartas/08 la botella.jpg' },
      { number: 9,  name: 'El Barril',      url: '/cartas/09 el barril.jpg' },
      { number: 10, name: 'El Arbol',       url: '/cartas/10 el arbol.jpg' },
      { number: 11, name: 'El Melon',       url: '/cartas/11 el melon.jpg' },
      { number: 12, name: 'El Valiente',    url: '/cartas/12 el valiente.jpg' },
      { number: 13, name: 'El Gorrito',     url: '/cartas/13 el gorrito.jpg' },
      { number: 14, name: 'La Muerte',      url: '/cartas/14 la muerte.jpg' },
      { number: 15, name: 'La Pera',        url: '/cartas/15 la pera.jpg' },
      { number: 16, name: 'La Bandera',     url: '/cartas/16 la bandera.jpg' },
      { number: 17, name: 'El Bandolon',    url: '/cartas/17 el bandolon.jpg' },
      { number: 18, name: 'El Violoncello', url: '/cartas/18 el violoncello.jpg' },
      { number: 19, name: 'La Garza',       url: '/cartas/19 la garza.jpg' },
      { number: 20, name: 'El Pajaro',      url: '/cartas/20 el pajaro.jpg' },
      { number: 21, name: 'La Mano',        url: '/cartas/21 la mano.jpg' },
      { number: 22, name: 'La Bota',        url: '/cartas/22 la bota.jpg' },
      { number: 23, name: 'La Luna',        url: '/cartas/23 la luna.jpg' },
      { number: 24, name: 'El Cotorro',     url: '/cartas/24 el cotorro.jpg' },
      { number: 25, name: 'El Borracho',    url: '/cartas/25 el borracho.jpg' },
      { number: 26, name: 'El Negrito',     url: '/cartas/26 el negrito.jpg' },
      { number: 27, name: 'El Corazon',     url: '/cartas/27 el corazon.jpg' },
      { number: 28, name: 'La Sandia',      url: '/cartas/28 la sandia.jpg' },
      { number: 29, name: 'El Tambor',      url: '/cartas/29 el tambor.jpg' },
      { number: 30, name: 'El Camaron',     url: '/cartas/30 el camaron.jpg' },
      { number: 31, name: 'Las Jaras',      url: '/cartas/31 las jaras.jpg' },
      { number: 32, name: 'El Musico',      url: '/cartas/32 el musico.jpg' },
      { number: 33, name: 'La Araña',       url: '/cartas/33 la araña.jpg' },
      { number: 34, name: 'El Soldado',     url: '/cartas/34 el soldado.jpg' },
      { number: 35, name: 'La Estrella',    url: '/cartas/35 la estrella.jpg' },
      { number: 36, name: 'El Cazo',        url: '/cartas/36 el cazo.jpg' },
      { number: 37, name: 'El Mundo',       url: '/cartas/37 el mundo.jpg' },
      { number: 38, name: 'El Apache',      url: '/cartas/38 el apache.jpg' },
      { number: 39, name: 'El Nopal',       url: '/cartas/39 el nopal.jpg' },
      { number: 40, name: 'El Alacran',     url: '/cartas/40 el alacran.jpg' },
      { number: 41, name: 'La Rosa',        url: '/cartas/41 la rosa.jpg' },
      { number: 42, name: 'La Calavera',    url: '/cartas/42 la calavera.jpg' },
      { number: 43, name: 'La Campana',     url: '/cartas/43 la campana.jpg' },
      { number: 44, name: 'El Cantarito',   url: '/cartas/44 el cantarito.jpg' },
      { number: 45, name: 'El Venado',      url: '/cartas/45 el venado.jpg' },
      { number: 46, name: 'El Sol',         url: '/cartas/46 el sol.jpg' },
      { number: 47, name: 'La Corona',      url: '/cartas/47 la corona.jpg' },
      { number: 48, name: 'La Chalupa',     url: '/cartas/48 la chalupa.jpg' },
      { number: 49, name: 'El Pino',        url: '/cartas/49 el pino.jpg' },
      { number: 50, name: 'El Pescado',     url: '/cartas/50 el pescado.jpg' },
      { number: 51, name: 'La Palmera',     url: '/cartas/51 la palma.jpg' },
      { number: 52, name: 'La Maceta',      url: '/cartas/52 la maceta.jpg' },
      { number: 53, name: 'El Arpa',        url: '/cartas/53 el arpa.jpg' },
      { number: 54, name: 'La Rana',        url: '/cartas/54 la rana.jpg' },
    ];

    await Card.createMany(cartas)
  }
}
